elevator:
joint_state_controller
		type: joint_state_controller/JointStateController
		publish rate: 50

	door_to_ground_joint_position_controller:
		type: effort_controllers/JointPositionController
		joint: door_ground_joint
		pid: {p: 1.0, i: 1.0, d: 1.0}